site_name: Projeto final de Silvia Rocha - Curso de Introdução à Qualidade de Software - FEST-UFF
theme:
  icon:
    admonition:
      warning: material/alert
    annotation: material/arrow-right-circle
  favicon: favicon.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  
nav:
  - 'index.md'
  - 'projetot2m.md'
  - 'planejamentotestes.md'



